apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: POSTGRES_PASSWORD

          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

          volumeMounts:
            - name: payment-db-data
              mountPath: /var/lib/postgresql

      volumes:
        - name: payment-db-data
          persistentVolumeClaim:
            claimName: payment-db-data

---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
spec:
  type: ClusterIP
  selector:
    app: payment-db
  ports:
    - port: 5432
      targetPort: 5432